window.env = {
  "TERM_PROGRAM": "Apple_Terminal",
  "NODE": "/usr/local/Cellar/node/16.6.1/bin/node",
  "INIT_CWD": "/Users/sikachev/Developer/study/react/casper-qr",
  "NVM_CD_FLAGS": "-q",
  "npm_package_dependencies_axios": "^0.22.0",
  "npm_package_homepage": "https://cy6erninja.github.io/casper-qr-code",
  "npm_config_version_git_tag": "true",
  "SHELL": "/bin/zsh",
  "TERM": "xterm-256color",
  "npm_package_dependencies_react_dotenv": "^0.1.3",
  "TMPDIR": "/var/folders/91/t6gr12716zvbdg5ncx9gb_n00000gp/T/",
  "npm_package_dependencies_casper_js_sdk": "^2.6.0",
  "npm_config_metrics_registry": "https://registry.yarnpkg.com/",
  "GOBIN": "/Users/sikachev/go/bin",
  "npm_package_dependencies_react_bootstrap": "^2.0.0-rc.0",
  "npm_config_init_license": "MIT",
  "TERM_PROGRAM_VERSION": "440",
  "TERM_SESSION_ID": "B5D0189F-2000-43E4-9A2A-FE15AC3460BB",
  "COLOR": "1",
  "npm_package_private": "true",
  "npm_config_registry": "https://registry.yarnpkg.com",
  "npm_config_noproxy": "",
  "ZSH": "/Users/sikachev/.oh-my-zsh",
  "npm_package_dependencies_react_dom": "^17.0.2",
  "npm_package_readmeFilename": "README.md",
  "USER": "sikachev",
  "NVM_DIR": "/Users/sikachev/.nvm",
  "npm_package_description": "This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).",
  "npm_package_dependencies_web_vitals": "^1.0.1",
  "npm_package_scripts_deploy": "gh-pages -d build",
  "npm_package_dependencies__testing_library_user_event": "^12.1.10",
  "npm_package_browserslist_development_1": "last 1 firefox version",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "npm_package_browserslist_development_0": "last 1 chrome version",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.iKrGnzeKAx/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F6:0x0:0x0",
  "npm_package_browserslist_development_2": "last 1 safari version",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "npm_package_scripts_predeploy": "npm run build",
  "PAGER": "less",
  "npm_package_dependencies_react_alert_template_basic": "^1.0.2",
  "npm_package_dependencies_react_alert": "^7.0.3",
  "LSCOLORS": "Gxfxcxdxbxegedabagacad",
  "PATH": "/Users/sikachev/Developer/study/react/casper-qr/node_modules/.bin:/Users/sikachev/Developer/study/react/node_modules/.bin:/Users/sikachev/Developer/study/node_modules/.bin:/Users/sikachev/Developer/node_modules/.bin:/Users/sikachev/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/var/folders/91/t6gr12716zvbdg5ncx9gb_n00000gp/T/yarn--1633783206689-0.15497847300791667:/Users/sikachev/Developer/study/react/casper-qr/node_modules/.bin:/Users/sikachev/.config/yarn/link/node_modules/.bin:/usr/local/Cellar/node/16.6.1/libexec/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/Cellar/node/16.6.1/lib/node_modules/npm/bin/node-gyp-bin:/usr/local/Cellar/node/16.6.1/bin/node_modules/npm/bin/node-gyp-bin:/Users/sikachev/.local/share/solana/install/active_release/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Users/sikachev/.vimpkg/bin:/Users/sikachev/go/bin:/usr/local/go/bin:/Users/sikachev/.cargo/bin:/Users/sikachev/custom/telegram-bot-api/bin",
  "npm_config_argv": "{\"remain\":[],\"cooked\":[\"run\",\"predeploy\"],\"original\":[\"deploy\"]}",
  "_": "/Users/sikachev/Developer/study/react/casper-qr/node_modules/.bin/react-dotenv",
  "npm_package_json": "/Users/sikachev/Developer/study/react/casper-qr/package.json",
  "__CFBundleIdentifier": "com.apple.Terminal",
  "npm_package_browserslist_production_1": "not dead",
  "npm_config_init_module": "/Users/sikachev/.npm-init.js",
  "npm_config_userconfig": "/Users/sikachev/.npmrc",
  "PWD": "/Users/sikachev/Developer/study/react/casper-qr",
  "npm_package_browserslist_production_0": ">0.2%",
  "npm_package_dependencies_bootstrap": "5.1.1",
  "npm_command": "run-script",
  "npm_lifecycle_event": "build",
  "npm_package_browserslist_production_2": "not op_mini all",
  "EDITOR": "vi",
  "npm_package_name": "casper-qr",
  "npm_package_scripts_build": "react-dotenv && react-scripts build",
  "npm_package_scripts_start": "react-dotenv && react-scripts start",
  "npm_config_version_commit_hooks": "true",
  "XPC_FLAGS": "0x0",
  "npm_config_bin_links": "true",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "XPC_SERVICE_NAME": "0",
  "npm_package_version": "0.1.0",
  "SHLVL": "3",
  "HOME": "/Users/sikachev",
  "npm_package_dependencies_gh_pages": "^3.2.3",
  "npm_package_scripts_test": "react-dotenv && react-scripts test",
  "npm_config_save_prefix": "^",
  "npm_config_strict_ssl": "true",
  "npm_package_dependencies__testing_library_jest_dom": "^5.11.4",
  "npm_config_version_git_message": "v%s",
  "API_URL": "http://127.0.0.1:8114",
  "LOGNAME": "sikachev",
  "LESS": "-R",
  "YARN_WRAP_OUTPUT": "false",
  "npm_package_dependencies_react_scripts": "4.0.3",
  "npm_package_dependencies_qrcode_react": "^1.0.1",
  "npm_config_cache": "/Users/sikachev/.npm",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "LC_CTYPE": "UTF-8",
  "npm_package_eslintConfig_extends_1": "react-app/jest",
  "npm_package_dependencies_react": "^17.0.2",
  "GITHUB_TOKEN": "c2f89226caa4cc95d222ea7881a0ee2277a3c643",
  "GOPATH": "/Users/sikachev/go",
  "npm_package_eslintConfig_extends_0": "react-app",
  "npm_package_dependencies__testing_library_react": "^11.1.0",
  "npm_config_version_git_sign": "",
  "npm_config_ignore_scripts": "",
  "npm_config_user_agent": "yarn/1.22.4 npm/? node/v16.6.1 darwin x64",
  "npm_config_init_version": "1.0.0",
  "npm_config_ignore_optional": "",
  "npm_package_scripts_eject": "react-scripts eject",
  "npm_node_execpath": "/usr/local/Cellar/node/16.6.1/bin/node",
  "npm_config_version_tag_prefix": "v",
  "npm_config_prefix": "/usr/local",
  "IMGBB_BASE": "https://api.imgbb.com/1/upload",
  "IMGBB_EXPIRATION": "1000",
  "IMGBB_API_KEY": "01f871ad56b2137b3affb38dfd46ae31"
};